# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fund Notifier Cronjob

on:
  schedule:
    - cron: "00 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main script
      run: |
        python ./src/fund_rich_notifier.py
      env:
        user_id: ${{ secrets.USER_ID }}
        password: ${{ secrets.PASSWORD }}
        mailgun_domain: ${{ secrets.MAILGUN_DOMAIN }}
        mailgun_token: ${{ secrets.MAILGUN_TOKEN }}
        recipient: ${{ secrets.RECIPIENT }}
